version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: formlog-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: formlog
    volumes:
      - mongodb_data:/data/db
    networks:
      - formlog-network

volumes:
  mongodb_data:

networks:
  formlog-network:
    driver: bridge 